### ISSUE TITLE
Создать telegram бота

### ISSUE THREAD

**Issue by EugeneT1024** [YourCodeReview/java-01-task-3#2]
Имя бота - @YourPersonalFinancesBot

В комментарии к задаче указать:
1. Ссылку на гайд по которому создавался бот
2. Идентификаторы для созданного бота

**Comment by DennisYudin** [comment]
1. Ссылку на гайд по которому создавался бот (https://www.youtube.com/watch?v=IX3B87hqF4Y&list=LL&index=2&t=2717s)
2. Идентификаторы для созданного бота:
userName - @YourPersonalFinancesBot
token - 5081965209:AAEqZLb0UW0kLvgt3rl7PCqHPD0t8MTJ3hY
